---
os: linux
arch: amd64
dist: bionic

language: python
cache: pip
services: docker

install:
  - pip install -r https://raw.githubusercontent.com/marverix/ansible-roles-common/latest/test-requirements.txt

script:
  - molecule --base-config molecule/base.yml test --scenario-name default
  - molecule --base-config molecule/base.yml test --scenario-name python3.6
  - molecule --base-config molecule/base.yml test --scenario-name python3.7
  - molecule --base-config molecule/base.yml test --scenario-name python3.8
  - molecule --base-config molecule/base.yml test --scenario-name python3.9
  - molecule --base-config molecule/base.yml test --scenario-name python3.6-source-only
  - molecule --base-config molecule/base.yml test --scenario-name python3.9-link

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
