---
- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Install
      apt:
        name: "python{{ python3_version }}"
        update_cache: yes
      
    - name: Install distutils (optional)
      apt:
        name: "python{{ python3_version }}-distutils"
      failed_when: false

- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Install (Centos)
      yum:
        name: "python{{ python3_version | replace('.', '') }}"
        update_cache: yes

- name: Download get-pip.py
  get_url:
    url: "{{ python3_get_pip_url }}"
    dest: "{{ python3_get_pip_tmp }}"
  register: response
  changed_when: "response.status_code != 200"

- name: Install pip
  command:
    cmd: "python{{ python3_version }} {{ python3_get_pip_tmp }}"
  changed_when: false

- name: Clean
  file:
    path: "{{ python3_get_pip_tmp }}"
    state: absent
  changed_when: false
