---
- name: Install dependencies
  apt:
    name: software-properties-common

- name: Add repository
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install
  apt:
    name: "python{{ python3_version }}"
    update_cache: yes
