---
- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Install
      apt:
        name: "python{{ python3_version }}"
        update_cache: yes

- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Install
      yum:
        name: "python{{ python3_version | replace('.', '') }}"
        update_cache: yes
