---
- name: Set facts
  set_fact:
    python3_install_from: "{{ python3_source_matrix[ansible_distribution + '_' + ansible_distribution_major_version][python3_version] }}"

- name: Install from official repo
  when: python3_install_from == 'official' and not python3_only_from_source
  include_tasks: from-official.yml

- name: Install from deadsnakes ppa
  when: python3_install_from == 'deadsnakes' and not python3_only_from_source
  include_tasks: from-deadsnakes.yml

- name: Install from source
  when: python3_install_from == 'source' or python3_only_from_source
  include_tasks: from-source.yml

- name: Update pip
  pip:
    name: pip
    version: "{{ python3_pip_version }}"
    extra_args: --upgrade
    executable: "/usr/local/bin/pip{{ python3_version }}"

- name: Set links
  when: python3_link or python3_pip_link
  include_tasks: set-links.yml
