---
- name: /usr/bin/python3
  file:
    src: "/usr/bin/python{{ python3_version }}"
    dest: "/usr/bin/python3"
    state: link
  when: python3_link

- name: /usr/bin/pip3
  file:
    src: "/usr/bin/pip{{ python3_version }}"
    dest: "/usr/bin/pip3"
    state: link
  when: python3_pip_link
