---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: ubuntu18
    image: bitbar/ubupy:bionic
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  - name: ubuntu20
    image: bitbar/ubupy:focal
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  - name: centos7
    image: pycontribs/centos:7
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

provisioner:
  name: ansible

verifier:
  name: ansible

scenario:
  test_sequence:
    # - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
