---
- name: Verify
  hosts: all
  tasks:

    - name: Run python3.7 command
      shell: "python3.7 --version"
      register: test

    - name: Assert result
      assert:
        that: "'Python 3.7' in test.stdout"

    - name: Run python3.7 command
      shell: "python3.7 -c 'print(list(map(lambda it: -it, [-1, 1])))'"
      register: test

    - name: Assert result
      assert:
        that: "test.stdout == '[1, -1]'"
